# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MyRaylibProject_config = debug
  raylib_config = debug

else ifeq ($(config),release)
  MyRaylibProject_config = release
  raylib_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MyRaylibProject raylib

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MyRaylibProject: raylib
ifneq (,$(MyRaylibProject_config))
	@echo "==== Building MyRaylibProject ($(MyRaylibProject_config)) ===="
	@${MAKE} --no-print-directory -C . -f MyRaylibProject.make config=$(MyRaylibProject_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C . -f raylib.make config=$(raylib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MyRaylibProject.make clean
	@${MAKE} --no-print-directory -C . -f raylib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MyRaylibProject"
	@echo "   raylib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"